'use strict';
const {Plugin, ItemView, Notice}=require('obsidian');
const TYPE='cortex-mobile-view', DAY=86400000, TAU=Math.PI*2;
const DEFAULTS={mode:'organism',vantage:'contained',palette:'deep',flow:1,bloom:0,quality:'low',names:'hubs',headings:false,pull:'links',focusView:'dim'};
let FOLDER_T={};
let MUTE={};
let PALE={"_root":0.55};
let FOLDER_OVERRIDE={};
// Portable colour mapping. The original build hard-coded one vault's folder names;
// this derives the ramp from whatever top-level folders the vault actually has, so the
// busiest working area sits at the hot end and support folders stay muted. A `folders`
// object in data.json overrides the derivation entirely.
const SUPPORT=/^(archive|archives|attachments|attachment|templates|template|inbox|library|maps|skills|jobs|assets|meta|_root)$/i;
const bare=f=>f.replace(/^[0-9]+[-_. ]*/,'');
const isArchive=f=>/archive/i.test(bare(f));
const isSupport=f=>f!=='_root'&&(f.startsWith('_')||SUPPORT.test(bare(f)));
function deriveFolders(nodes){
 const count=new Map();
 for(const n of nodes)if(n.kind==='note')count.set(n.folder,(count.get(n.folder)||0)+1);
 if(Object.keys(FOLDER_OVERRIDE).length){FOLDER_T={_root:0.55,...FOLDER_OVERRIDE};}
 else{
  const work=[...count.keys()].filter(f=>f!=='_root'&&!isSupport(f)&&!isArchive(f))
   .sort((a,b)=>(count.get(b)-count.get(a))||a.localeCompare(b));
  FOLDER_T={_root:0.55};
  work.forEach((f,i)=>{FOLDER_T[f]=work.length<2?1:1-(i/(work.length-1))*0.75;});
  for(const f of count.keys()){if(isArchive(f))FOLDER_T[f]=0;else if(isSupport(f))FOLDER_T[f]=0.12;}
 }
 MUTE={};
 for(const f of count.keys()){if(isArchive(f))MUTE[f]=0.22;else if(isSupport(f))MUTE[f]=0.62;}
}
const PALETTES={deep:['#1B4F9C','#2C7FD6','#3FA9E8','#5B7BE8','#7B5CFF','#A855F7','#DC5FC6'],bloom:['#2FB8E8','#4E8CFF','#7B5CFF','#A855F7','#D946C8','#FF6FB5','#FFB3D9'],violet:['#3E44C4','#5A4BDC','#7A4FEC','#A855F7','#C24FE6','#DE55D6','#F074CE']};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const heat=d=>Math.exp(-Math.max(0,d)/18);
const rgb=h=>[(parseInt(h.slice(1),16)>>16)&255,(parseInt(h.slice(1),16)>>8)&255,parseInt(h.slice(1),16)&255];
const mix=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t);
const css=c=>'rgb('+c.map(Math.round).join(',')+')';
function folderColor(folder,palette){const p=PALETTES[palette],t=(FOLDER_T[folder]??.3)*(p.length-1),i=Math.min(p.length-2,Math.floor(t));let c=mix(rgb(p[i]),rgb(p[i+1]),t-i);if(MUTE[folder])c=mix(rgb('#0A0620'),c,MUTE[folder]);if(PALE[folder])c=mix(c,[255,240,252],PALE[folder]);return c;}
function parseHistory(raw){const result=new Map();let stamp=0;for(const line of raw.split('\n')){if(/^C\d+$/.test(line)){stamp=Number(line.slice(1))*1000;continue;}if(!line||!stamp)continue;let path=line;if(path[0]==='"'){try{path=JSON.parse(path);}catch{continue;}}if(!result.has(path))result.set(path,[]);result.get(path).push(stamp);}for(const times of result.values())times.sort((a,b)=>a-b);return result;}
function lastAt(times,now){if(!times?.length||times[0]>now)return null;let lo=0,hi=times.length;while(lo<hi){const mid=(lo+hi)>>>1;if(times[mid]<=now)lo=mid+1;else hi=mid;}return times[lo-1];}
function buildGraph(files,cache,resolved,history,now=Date.now()){
 const nodes=[],edges=[],index=new Map();
 for(const file of files){const times=history.get(file.path)||[];index.set(file.path,nodes.length);nodes.push({id:file.path,name:file.basename,path:file.path,kind:'note',folder:file.path.includes('/')?file.path.split('/')[0]:'_root',degree:0,heatDays:(now-(times.at(-1)??file.stat.mtime))/DAY,commits:times.length,parent:null,times,mtime:file.stat.mtime});}
 for(const file of files){const root=nodes[index.get(file.path)],stack=[];for(const [j,h] of (cache(file)?.headings||[]).entries()){while(stack.length&&stack.at(-1).level>=h.level)stack.pop();const parent=stack.length?stack.at(-1).id:file.path,id=file.path+'#'+j;index.set(id,nodes.length);nodes.push({...root,id,name:h.heading,kind:'heading',degree:0,parent,heading:h.heading,line:h.position?.start?.line??0});edges.push([index.get(parent),nodes.length-1,1]);stack.push({id,level:h.level});}}
 const seen=new Set();for(const [source,targets]of Object.entries(resolved||{})){const a=index.get(source);if(a===undefined)continue;for(const target of Object.keys(targets)){const b=index.get(target);if(b===undefined||a===b)continue;const key=Math.min(a,b)+':'+Math.max(a,b);if(!seen.has(key)){seen.add(key);edges.push([a,b,0]);}}}
 const adjacency=nodes.map(()=>[]);for(const [a,b]of edges){nodes[a].degree++;nodes[b].degree++;adjacency[a].push(b);adjacency[b].push(a);}deriveFolders(nodes);return {nodes,edges,adjacency,index,noteCount:files.length};
}
// A bounded spatial grid approximates far-field repulsion using each cell's centroid.
// The grid is reused across iterations; close cells evaluate individual neighbours.
class Layout{
 constructor(graph,pull){this.graph=graph;this.pull=pull;const n=graph.nodes.length;this.pos=new Float64Array(n*3);this.force=new Float64Array(n*3);this.vel=new Float64Array(n*3);this.next=new Int32Array(n);this.head=new Int32Array(512);this.count=new Int32Array(512);this.centers=new Float64Array(1536);this.iterations=0;const folders=[...new Set(graph.nodes.map(n=>n.folder))];let seed=20260913;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<n;i++){const node=graph.nodes[i],fi=folders.indexOf(node.folder),a=fi/folders.length*TAU,z=(fi%5)/5*2-1,r=1600+random()*560,s=Math.sqrt(1-z*z);this.pos[i*3]=Math.cos(a)*s*r+(random()-.5)*500;this.pos[i*3+1]=z*r+(random()-.5)*500;this.pos[i*3+2]=Math.sin(a)*s*r+(random()-.5)*500;}this.maxDeg=Math.max(1,...graph.nodes.map(n=>n.degree));}
 step(){const {pos:p,force:f,graph:g}=this,n=g.nodes.length;if(!n)return;this.head.fill(-1);this.count.fill(0);this.centers.fill(0);f.fill(0);let bound=1;for(let k=0;k<p.length;k++)bound=Math.max(bound,Math.abs(p[k]));const cell=bound*2/8;
 for(let i=0;i<n;i++){const k=i*3,x=clamp(Math.floor((p[k]+bound)/cell),0,7),y=clamp(Math.floor((p[k+1]+bound)/cell),0,7),z=clamp(Math.floor((p[k+2]+bound)/cell),0,7),c=x+y*8+z*64;this.next[i]=this.head[c];this.head[c]=i;this.count[c]++;for(let d=0;d<3;d++)this.centers[c*3+d]+=p[k+d];}
 for(let c=0;c<512;c++)if(this.count[c])for(let d=0;d<3;d++)this.centers[c*3+d]/=this.count[c];
 for(let i=0;i<n;i++){const k=i*3;for(let c=0;c<512;c++){if(!this.count[c])continue;const dx=p[k]-this.centers[c*3],dy=p[k+1]-this.centers[c*3+1],dz=p[k+2]-this.centers[c*3+2],d2=dx*dx+dy*dy+dz*dz+64;if(d2>cell*cell*3){const scale=1800*this.count[c]/(d2*Math.sqrt(d2));f[k]+=dx*scale;f[k+1]+=dy*scale;f[k+2]+=dz*scale;}else{for(let j=this.head[c];j>=0;j=this.next[j]){if(i===j)continue;const x=p[k]-p[j*3],y=p[k+1]-p[j*3+1],z=p[k+2]-p[j*3+2],dist=x*x+y*y+z*z+36,scale=1800/(dist*Math.sqrt(dist));f[k]+=x*scale;f[k+1]+=y*scale;f[k+2]+=z*scale;}}}}
 for(const [a,b,h]of g.edges){const ak=a*3,bk=b*3,dx=p[bk]-p[ak],dy=p[bk+1]-p[ak+1],dz=p[bk+2]-p[ak+2],dist=Math.hypot(dx,dy,dz)||1,s=(dist-(h?28:145))/dist*(h?.10:.012);f[ak]+=dx*s;f[ak+1]+=dy*s;f[ak+2]+=dz*s;f[bk]-=dx*s;f[bk+1]-=dy*s;f[bk+2]-=dz*s;}
 for(let i=0;i<n;i++){const node=g.nodes[i],hub=Math.log1p(node.degree)/Math.log1p(this.maxDeg),weight=this.pull==='links'?.35+hub*2.6:this.pull==='recency'?.35+heat(node.heatDays)*2.6:1.25;for(let d=0;d<3;d++){const k=i*3+d;this.vel[k]=(this.vel[k]+f[k]-p[k]*.006*weight)*.62;p[k]+=clamp(this.vel[k],-48,48);}}this.iterations++;}
 normalize(amount=1){const p=this.pos,n=p.length/3;if(!n)return;let x=0,y=0,z=0;for(let i=0;i<n;i++){x+=p[i*3];y+=p[i*3+1];z+=p[i*3+2];}let max=0;for(let i=0;i<n;i++){p[i*3]-=x/n*amount;p[i*3+1]-=y/n*amount;p[i*3+2]-=z/n*amount;max=Math.max(max,Math.hypot(p[i*3],p[i*3+1],p[i*3+2]));}for(let k=0;k<p.length;k++)p[k]*=1+(720/(max||1)-1)*amount;}
}
class CortexView extends ItemView{
 constructor(leaf,plugin){super(leaf);this.plugin=plugin;this.settings={...plugin.settings};this.yaw=0;this.pitch=.12;this.zoom=1;this.spinX=0;this.spinY=0;this.focus=-1;this.hover=-1;this.reach=1;this.anchor=-1;this.cursor=-1;this.trail=[];this.altHeld=false;this.branchCount=0;this.isolating=false;this.pointerX=-1000;this.pointerY=-1000;this.raf=0;this.closed=false;this.failures=0;this.frames=0;this.frameMs=0;this.layoutRuns=0;this.clock=0;this.last=0;this.morph=this.settings.mode==='telemetry'?1:0;this.morphFrom=this.morph;this.morphTarget=this.morph;this.target=new Float64Array(3);this.targetFrom=new Float64Array(3);this.targetTo=new Float64Array(3);this.sprites=new Map();this.pulseSlots=[];this.lastPulse=0;this.playStart=null;}
 getViewType(){return TYPE;}getDisplayText(){return 'Cortex';}getIcon(){return 'orbit';}
 async onOpen(){this.doc=this.contentEl.ownerDocument;this.win=this.doc.defaultView;this.reduced=this.win.matchMedia('(prefers-reduced-motion: reduce)').matches;this.contentEl.empty();this.contentEl.addClass('cortex');this.canvas=this.contentEl.createEl('canvas',{attr:{tabindex:'0','aria-label':'Cortex vault. Drag to orbit, scroll to zoom, click to follow a branch, click it again to open. Tab cycles the branch, arrow up and down change its reach, arrow right drills in, arrow left steps back, Enter opens, holding Alt isolates the branch. Click away or press Escape to release.'}});this.ctx=this.canvas.getContext('2d');this.header=this.contentEl.createDiv('cortex-header');this.header.createEl('h2',{text:'Spectre'});this.subtitle=this.header.createDiv({cls:'cortex-subtitle',text:'A living atlas of your thinking'});this.tally=this.contentEl.createDiv('cortex-tally');this.readout=this.contentEl.createDiv('cortex-readout');this.controls=this.contentEl.createDiv('cortex-controls');this.makeControls();this.bindInput();this.resizeObserver=new this.win.ResizeObserver(()=>{this.resize();this.syncVisibility();});this.resizeObserver.observe(this.contentEl);this.intersection=new this.win.IntersectionObserver(()=>this.syncVisibility());this.intersection.observe(this.contentEl);this.registerDomEvent(this.doc,'visibilitychange',()=>this.syncVisibility());this.registerEvent(this.app.workspace.on('layout-change',()=>this.syncVisibility()));this.registerEvent(this.app.workspace.on('active-leaf-change',()=>this.syncVisibility()));this.registerDomEvent(this.win,'resize',()=>this.resize());this.resize();await this.refresh();}
 makeControls(){const mode=this.controls.createDiv('cortex-modes');for(const value of ['organism','telemetry']){const b=mode.createEl('button',{text:value});b.setAttribute('aria-pressed',String(this.settings.mode===value));b.onclick=()=>{this.change('mode',value);for(const el of mode.children)el.setAttribute('aria-pressed',String(el.textContent===value));};}const row=this.controls.createDiv('cortex-primary');this.select(row,'Vantage','vantage',['contained','close','inside','fly-in']);this.playButton=row.createEl('button',{text:'Play history',attr:{'aria-label':'Play git history over thirty seconds'}});this.playButton.onclick=()=>{if(!this.historyAvailable){new Notice('Git history is unavailable for playback.');return;}this.playStart=this.playStart===null?this.clock:null;this.playButton.textContent=this.playStart===null?'Play history':'Stop playback';this.updateHeat();this.syncVisibility();};const details=this.controls.createEl('details');details.createEl('summary',{text:'Tune the view'});const grid=details.createDiv('cortex-options');this.paletteControl=this.select(grid,'Palette','palette',['deep','bloom','violet']);this.select(grid,'Quality','quality',['high','balanced','low']);this.select(grid,'Names','names',['hubs','all','none']);this.select(grid,'On focus','focusView',['dim','isolate']);this.select(grid,'Core pull','pull',['links','recency','even']);for(const key of ['flow','bloom']){const label=grid.createEl('label',{text:key}),range=label.createEl('input',{attr:{type:'range',min:'0',max:'2',step:'.05','aria-label':key}});range.value=this.settings[key];range.oninput=()=>this.change(key,Number(range.value));}const label=grid.createEl('label',{text:'Show headings'}),check=label.createEl('input',{attr:{type:'checkbox'}});check.checked=this.settings.headings;check.onchange=()=>this.change('headings',check.checked);this.controls.createDiv({cls:'cortex-hint',text:'Drag to orbit · scroll to zoom · click to follow · click again to open (⌘ same tab) · Tab cycles the branch · ↑↓ reach · → drill in · ← back · hold ⌥ to isolate · click away or Esc to release'});this.paletteControl.disabled=this.settings.mode==='telemetry';}
 select(host,label,key,values){const wrap=host.createEl('label',{text:label}),select=wrap.createEl('select', {attr:{'aria-label':label}});for(const value of values)select.createEl('option',{text:value,value});select.value=this.settings[key];select.onchange=()=>this.change(key,select.value);return select;}
 change(key,value){this.settings[key]=value;this.plugin.settings={...this.settings};this.plugin.saveData(this.plugin.settings).catch(e=>new Notice('Cortex could not save settings: '+e.message));if(key==='mode'){this.morphFrom=this.morph;this.morphTarget=value==='telemetry'?1:0;this.morphStart=this.clock;this.paletteControl.disabled=value==='telemetry';}if(key==='pull')this.startLayout();if(key==='palette')this.prepareColors();if(key==='vantage'){this.focus=-1;this.targetFrom.set(this.target);this.targetTo.fill(0);this.focusStart=this.clock;this.zoom=1;}this.syncVisibility();}
 async refresh(){if(this.closed)return;this.priorFocusId=this.focus>=0&&this.graph?this.graph.nodes[this.focus].id:null;const graph=await this.plugin.graph();if(this.closed)return;const signature=graph.nodes.map(n=>n.id).join('\0');const changed=signature!==this.signature;this.signature=signature;this.graph=graph;this.historyAvailable=graph.nodes.some(n=>n.times.length);this.historyMin=Math.min(Date.now(),...graph.nodes.filter(n=>n.times.length).map(n=>n.times[0]));this.historyMax=Date.now();this.focus=-1;this.hover=-1;this.highlight=new Uint8Array(graph.nodes.length);if(changed){const n=graph.nodes.length;this.proj=new Float32Array(n*3);this.drift=new Float32Array(n*3);this.reaction=new Float32Array(n*2);this.brightness=new Float32Array(n);this.heats=new Float32Array(n);this.alive=new Float32Array(n);this.flash=new Float32Array(n);this.pulseSlots=Array.from({length:4},()=>({start:-Infinity,arrival:new Float64Array(n)}));this.queue=new Int32Array(n);this.startLayout();}else if(this.layout)this.layout.graph=graph;this.updateHeat();this.prepareColors();if(!changed&&this.priorFocusId!=null){const i=graph.nodes.findIndex(x=>x.id===this.priorFocusId);if(i>=0){this.focus=i;this.anchor=i;this.cursor=-1;this.markConnections();}}if(this.focus<0){this.anchor=-1;this.cursor=-1;this.trail.length=0;}this.priorFocusId=null;this.syncVisibility();}
 startLayout(){if(!this.graph)return;this.layout=new Layout(this.graph,this.settings.pull);this.layoutRuns++;this.layoutStart=this.clock;this.layoutActive=true;if(this.reduced){for(let i=0;i<120;i++)this.layout.step();this.layout.normalize();this.layoutActive=false;}}
 prepareColors(){this.sprites.clear();const ramps=new Map();this.colors=this.graph.nodes.map(n=>{const c=folderColor(n.folder,this.settings.palette);if(!ramps.has(n.folder)){const cold=[],hot=[];for(let j=0;j<=24;j++){cold.push(css(mix(c,[154,170,184],j/24)));hot.push(css(mix(c,[255,158,61],j/24)));}ramps.set(n.folder,{cold,hot});}return {ramps:ramps.get(n.folder),organic:css(c),steel:'#9AAAB8',white:'#E8F0F6',amber:'#FF9E3D',normal:n.name,upper:n.name.toUpperCase()};});for(const c of this.colors){for(const ramp of [c.ramps.cold,c.ramps.hot])for(const color of ramp)for(const kind of ['halo','body','core'])this.sprite(color,kind);this.sprite('#FF9E3D','core');this.sprite('#E8F0F6','core');}}
 updateHeat(){if(!this.graph)return;const now=this.playStart===null?Date.now():this.historyMin+clamp((this.clock-this.playStart)/30000,0,1)*(this.historyMax-this.historyMin);this.playTime=now;const folders=new Map();for(let i=0;i<this.graph.nodes.length;i++){const n=this.graph.nodes[i],last=n.times.length?lastAt(n.times,now):(n.mtime<=now?n.mtime:null),age=last===null?Infinity:(now-last)/DAY;this.heats[i]=heat(age);this.alive[i]=last===null?0:clamp((now-(n.times[0]??n.mtime))/DAY*2,0,1);if(this.playStart===null)this.alive[i]=1;this.brightness[i]=age<7?1:0;if(n.kind==='note'){const v=folders.get(n.folder)||[0,0];v[0]+=this.heats[i];v[1]++;folders.set(n.folder,v);}}this.folderHeat=folders;this.heatUpdated=this.clock;}
 sprite(color,kind){const key=color+kind;if(this.sprites.has(key))return this.sprites.get(key);const canvas=this.doc.createElement('canvas');canvas.width=canvas.height=96;const ctx=canvas.getContext('2d'),g=ctx.createRadialGradient(48,48,0,48,48,48),c=rgb(color.startsWith('#')?color:'#ffffff');const raw=color.startsWith('rgb')?color.slice(4,-1):c.join(',');const stops=kind==='halo'?[[0,.30],[.06,.19],[.16,.095],[.34,.034],[.60,.010],[1,0]]:kind==='body'?[[0,.80],[.22,.60],[.46,.30],[.68,.10],[.86,.022],[1,0]]:[[0,1],[.28,.80],[.55,.32],[.80,.07],[1,0]];for(const [p,a]of stops)g.addColorStop(p,'rgba('+raw+','+a+')');ctx.fillStyle=g;ctx.fillRect(0,0,96,96);this.sprites.set(key,canvas);return canvas;}
 resize(){const r=this.contentEl.getBoundingClientRect();this.w=r.width;this.h=r.height;const dpr=Math.min(this.win.devicePixelRatio||1,2);this.canvas.width=Math.round(this.w*dpr);this.canvas.height=Math.round(this.h*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);}
 visible(){return !this.closed&&!this.doc.hidden&&this.contentEl.isConnected&&this.contentEl.getBoundingClientRect().width>0&&this.contentEl.getBoundingClientRect().height>0&&this.win.getComputedStyle(this.contentEl).visibility!=='hidden';}
 syncVisibility(){if(this.visible()&&this.graph&&this.failures<3){if(!this.raf){this.last=0;this.raf=this.win.requestAnimationFrame(t=>this.frame(t));}}else{this.win.cancelAnimationFrame(this.raf);this.raf=0;this.last=0;}}
 pulse(root){if(this.reduced||this.morphTarget>=1||root<0)return;const limit=this.settings.quality==='low'?1:this.settings.quality==='balanced'?2:4;let slot;for(let k=0;k<limit;k++)if(this.clock-this.pulseSlots[k].start>3500){slot=this.pulseSlots[k];break;}if(!slot)return;slot.start=this.clock;slot.arrival.fill(Infinity);let begin=0,end=1;this.queue[0]=root;slot.arrival[root]=0;while(begin<end){const i=this.queue[begin++];for(const j of this.graph.adjacency[i])if(slot.arrival[j]===Infinity){slot.arrival[j]=slot.arrival[i]+90;this.queue[end++]=j;}}}
 setFocus(i,mode){this.focus=i;this.targetFrom.set(this.target);for(let d=0;d<3;d++)this.targetTo[d]=i<0?0:this.layout.pos[i*3+d];this.focusStart=this.clock;if(mode!=='follow'){if(mode!=='restore'&&this.anchor>=0&&this.anchor!==i){this.trail.push(this.anchor);if(this.trail.length>32)this.trail.shift();}this.anchor=i;this.cursor=-1;}if(i<0){this.anchor=-1;this.cursor=-1;this.trail.length=0;}this.pulse(i);this.markConnections();}
 step(dir){if(this.anchor<0)return;const adj=this.graph.adjacency[this.anchor];if(!adj)return;const list=Array.from(adj).filter(j=>this.settings.headings||this.graph.nodes[j].kind!=='heading');if(!list.length)return;if(this.cursor<0)this.cursor=dir>0?-1:0;this.cursor=(this.cursor+dir+list.length)%list.length;this.setFocus(list[this.cursor],'follow');}
 openNode(i,newLeaf){if(i<0||!this.graph)return;if(this.lastOpen&&this.lastOpen.i===i&&this.clock-this.lastOpen.t<600)return;this.lastOpen={i,t:this.clock};const n=this.graph.nodes[i];this.app.workspace.openLinkText(n.path+(n.kind==='heading'?'#'+n.heading:''),'',newLeaf!==false,{eState:n.kind==='heading'?{line:n.line}:undefined});}
 markConnections(){this.highlight.fill(0);this.branchCount=0;const i=this.focus>=0?this.focus:this.hover;if(i<0)return;const reach=this.focus>=0?this.reach:1;this.highlight[i]=1;this.queue[0]=i;let begin=0,end=1;for(let level=0;level<reach;level++){const stop=end;for(let k=begin;k<stop;k++)for(const j of this.graph.adjacency[this.queue[k]])if(!this.highlight[j]){this.highlight[j]=1;this.queue[end++]=j;}begin=stop;if(end===stop)break;}this.branchCount=end;}
 pick(x,y){let best=-1,distance=30;for(let i=0;i<this.graph.nodes.length;i++){if(this.proj[i*3+2]<=0||!this.alive[i]||(this.focus>=0&&!this.highlight[i])||(!this.settings.headings&&this.graph.nodes[i].kind==='heading'))continue;const d=Math.hypot(this.proj[i*3]-x,this.proj[i*3+1]-y);if(d<distance){distance=d;best=i;}}return best;}
 bindInput(){this.touches=new Map();this.pinch=0;
  this.registerDomEvent(this.canvas,'pointerdown',e=>{this.touches.set(e.pointerId,{x:e.clientX,y:e.clientY});
   if(this.touches.size===2){const[a,b]=[...this.touches.values()];this.pinch=Math.hypot(a.x-b.x,a.y-b.y);this.drag=null;return;}
   this.canvas.focus();this.drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};this.spinX=this.spinY=0;this.canvas.setPointerCapture(e.pointerId);});this.registerDomEvent(this.canvas,'pointermove',e=>{this.altHeld=e.altKey;
   if(this.touches.has(e.pointerId))this.touches.set(e.pointerId,{x:e.clientX,y:e.clientY});
   if(this.touches.size===2){const[a,b]=[...this.touches.values()],d=Math.hypot(a.x-b.x,a.y-b.y);
    if(this.pinch>0&&d>0)this.zoom=clamp(this.zoom*(d/this.pinch),.35,4);this.pinch=d;this.syncVisibility();return;}const r=this.canvas.getBoundingClientRect();this.pointerX=e.clientX-r.left;this.pointerY=e.clientY-r.top;if(this.drag){const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;this.yaw+=dx*.006;this.pitch=clamp(this.pitch-dy*.006,-1.35,1.35);this.spinX=dx*.006;this.spinY=-dy*.006;this.drag.x=e.clientX;this.drag.y=e.clientY;if(Math.hypot(e.clientX-this.drag.startX,e.clientY-this.drag.startY)>5)this.drag.moved=true;}else{this.hover=this.pick(this.pointerX,this.pointerY);this.markConnections();}this.syncVisibility();});this.registerDomEvent(this.canvas,'pointerup',e=>{this.touches.delete(e.pointerId);if(this.touches.size<2)this.pinch=0;
   if(this.drag&&!this.drag.moved){const i=this.pick(this.pointerX,this.pointerY);if(i>=0&&i===this.focus)this.openNode(i,!(e.metaKey||e.ctrlKey));else this.setFocus(i);}this.drag=null;if(this.canvas.hasPointerCapture(e.pointerId))this.canvas.releasePointerCapture(e.pointerId);});this.registerDomEvent(this.canvas,'pointercancel',e=>{this.touches.delete(e.pointerId);this.pinch=0;this.drag=null;this.spinX=this.spinY=0;});this.registerDomEvent(this.canvas,'pointerleave',()=>{this.pointerX=this.pointerY=-1000;this.hover=-1;this.markConnections();});this.registerDomEvent(this.canvas,'wheel',e=>{e.preventDefault();this.zoom=clamp(this.zoom*Math.exp(-e.deltaY*.001),.35,4);this.syncVisibility();},{passive:false});this.registerDomEvent(this.contentEl,'keydown',e=>{this.altHeld=e.altKey;const k=e.key;if(k==='Escape')this.setFocus(-1);else if(k==='Tab'&&this.anchor>=0)this.step(e.shiftKey?-1:1);else if((k==='ArrowUp'||k==='ArrowDown')&&this.focus>=0){this.reach=clamp(this.reach+(k==='ArrowUp'?1:-1),1,3);this.markConnections();}else if(k==='ArrowRight'&&this.focus>=0)this.setFocus(this.focus);else if((k==='ArrowLeft'||k==='Backspace')&&this.trail.length)this.setFocus(this.trail.pop(),'restore');else if(k==='Enter'&&this.focus>=0)this.openNode(this.focus,!(e.metaKey||e.ctrlKey));else{this.syncVisibility();return;}e.preventDefault();this.syncVisibility();});this.registerDomEvent(this.contentEl,'keyup',e=>{this.altHeld=e.altKey;this.syncVisibility();});}
 frame(t){this.raf=0;if(!this.visible())return;const started=this.win.performance.now(),dt=Math.min(50,this.last?t-this.last:16.67);this.last=t;this.clock+=dt;try{this.draw(dt);this.failures=0;this.frames++;this.frameMs=this.frameMs*.96+(this.win.performance.now()-started)*.04;}catch(e){console.error('Cortex render failure',e);if(++this.failures>=3){this.readout.textContent='Cortex paused after a rendering error. Close and reopen this view.';return;}}if(!this.reduced||this.layoutActive||Math.abs(this.morph-this.morphTarget)>.001||this.playStart!==null)this.raf=this.win.requestAnimationFrame(t=>this.frame(t));}
 draw(dt){const ctx=this.ctx,g=this.graph,n=g.nodes.length,s=this.settings;this.isolating=this.focus>=0&&((s.focusView==='isolate')!==!!this.altHeld);let entrance=1;if(this.layoutActive){const begin=this.win.performance.now();do{this.layout.step();}while(this.win.performance.now()-begin<6&&this.layout.iterations<120);entrance=clamp((this.clock-this.layoutStart)/2000,0,1);if(entrance>.7)this.layout.normalize(.12);if(entrance===1){this.layout.normalize();this.layoutActive=false;}}
 if(!this.reduced&&!this.drag){this.yaw+=.02*dt/1000+this.spinX*dt/16.67;this.pitch=clamp(this.pitch+this.spinY*dt/16.67,-1.35,1.35);this.spinX*=Math.pow(.94,dt/16.67);this.spinY*=Math.pow(.94,dt/16.67);}this.morph=this.reduced?this.morphTarget:this.morphFrom+(this.morphTarget-this.morphFrom)*ease(clamp((this.clock-(this.morphStart??0))/900,0,1));const m=this.morph;const colorStep=Math.round(m*24);
 const focusT=this.reduced?1:ease(clamp((this.clock-(this.focusStart??0))/600,0,1));for(let d=0;d<3;d++)this.target[d]=this.targetFrom[d]+(this.targetTo[d]-this.targetFrom[d])*focusT;
 if(this.playStart!==null&&this.clock-this.playStart>=30000){this.playStart=null;this.playButton.textContent='Play history';this.updateHeat();}if(this.clock-this.heatUpdated>(this.playStart===null?60000:150))this.updateHeat();if(m<1&&this.clock-this.lastPulse>2000){for(let tries=0;tries<20;tries++){const root=Math.floor(Math.random()*n);if(this.heats[root]>.65){this.pulse(root);break;}}this.lastPulse=this.clock;}
 this.flash.fill(0);for(const p of this.pulseSlots)if(this.clock-p.start<3500){for(let i=0;i<n;i++){const age=this.clock-p.start-p.arrival[i];if(age>=0&&age<700)this.flash[i]=Math.max(this.flash[i],Math.exp(-age/180)*(1-m));}}
 const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),p=this.layout.pos;const contained=1750*(1+(1-entrance)*.6),distance=s.vantage==='inside'?30:s.vantage==='close'?980:s.vantage==='fly-in'&&this.focus>=0?contained+(420-contained)*focusT:contained;this.distance=distance;const zoom=Math.min(this.w,this.h)/1900*this.zoom;this.scale=zoom;
 for(let i=0;i<n;i++){const k=i*3,x=p[k],y=p[k+1],z=p[k+2],amplitude=this.reduced?0:s.flow*(1-.75*m)*(.05+this.heats[i]*.95)*(this.focus>=0&&!this.highlight[i]?.12:1),time=this.clock*.00016,lag=1-Math.exp(-dt/280);this.drift[k]+=( (Math.sin(y*.002+time)+Math.cos(z*.0015-time*.7))*16*amplitude-this.drift[k])*lag;this.drift[k+1]+=((Math.sin(z*.002+time*.8)+Math.cos(x*.0018+time)) *16*amplitude-this.drift[k+1])*lag;this.drift[k+2]+=((Math.sin(x*.002-time*.9)+Math.cos(y*.0016+time*.7))*16*amplitude-this.drift[k+2])*lag;const xx=x+this.drift[k]-this.target[0],yy=y+this.drift[k+1]-this.target[1],zz=z+this.drift[k+2]-this.target[2],x1=xx*cy-zz*sy,z1=xx*sy+zz*cy,y2=yy*cp-z1*sp,z2=yy*sp+z1*cp,den=distance+z2,scale=den<35?0:1750/den;let sx=this.w/2+x1*scale*zoom,sy2=this.h/2-y2*scale*zoom;const dx=sx-this.pointerX,dy=sy2-this.pointerY,dist=Math.hypot(dx,dy)||1,force=this.reduced||(this.focus>=0&&!this.highlight[i])?0:Math.max(0,1-dist/90)*12*(1-m);this.reaction[i*2]+=(dx/dist*force-this.reaction[i*2])*lag;this.reaction[i*2+1]+=(dy/dist*force-this.reaction[i*2+1])*lag;this.proj[k]=sx+this.reaction[i*2];this.proj[k+1]=sy2+this.reaction[i*2+1];this.proj[k+2]=scale;}
 ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';ctx.fillStyle=m===1?'#05070A':m===0?'#04020E':css(mix([4,2,14],[5,7,10],m));ctx.fillRect(0,0,this.w,this.h);ctx.globalCompositeOperation='lighter';
 if(m<1&&s.bloom>0){const heart=this.sprite('#5B7BE8','halo');ctx.globalAlpha=.7*(1-m)*s.bloom;const r=Math.min(this.w,this.h)*.6;ctx.drawImage(heart,this.w/2-r,this.h/2-r,r*2,r*2);}
 const stride=s.quality==='high'?3:s.quality==='balanced'?8:20;
 for(let e=0;e<g.edges.length;e++){const [a,b,hierarchy]=g.edges[e];if(!s.headings&&hierarchy)continue;if(this.isolating&&!(this.highlight[a]&&this.highlight[b]))continue;const ak=a*3,bk=b*3;if(this.proj[ak+2]<=0||this.proj[bk+2]<=0)continue;const visibility=Math.min(this.alive[a],this.alive[b]);if(visibility<=0)continue;const lit=this.highlight[a]&&this.highlight[b],dim=this.focus>=0&&!lit?.06:1,hot=this.brightness[a]&&this.brightness[b],x=this.proj[ak],y=this.proj[ak+1],xx=this.proj[bk],yy=this.proj[bk+1],dx=xx-x,dy=yy-y,bend=(1-m)*.16,qx=(x+xx)/2-dy*bend,qy=(y+yy)/2+dx*bend;ctx.globalAlpha=visibility*dim*(lit?.65:hierarchy?.16:.22)*(.3+Math.max(this.heats[a],this.heats[b])*.7);ctx.lineWidth=lit?1.1:.55;ctx.strokeStyle=this.colors[a].ramps[hot?'hot':'cold'][colorStep];ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(qx,qy,xx,yy);ctx.stroke();if(e%stride===0&&!this.reduced){const u=(this.clock*.0001+e*.317)%1,v=1-u,px=v*v*x+2*v*u*qx+u*u*xx,py=v*v*y+2*v*u*qy+u*u*yy;ctx.globalAlpha=visibility*dim*.5;ctx.fillStyle=m>.5?(hot?'#FF9E3D':'#E8F0F6'):this.colors[a].organic;if(m>.5)ctx.fillRect(px-1,py-1,2,2);else ctx.drawImage(this.sprite(this.colors[a].organic,'core'),px-4,py-4,8,8);}}
 for(let i=0;i<n;i++){const node=g.nodes[i],k=i*3,depth=this.proj[k+2],heading=node.kind==='heading';if(depth<=0||!this.alive[i]||(this.isolating&&!this.highlight[i])||heading&&(!s.headings||s.quality==='low'&&depth<.85))continue;const x=this.proj[k],y=this.proj[k+1];if(x< -50||x>this.w+50||y< -50||y>this.h+50)continue;const hub=Math.log1p(node.degree)/Math.log1p(this.layout.maxDeg),r=clamp((heading?1.1:3+hub*7)*depth*zoom*1.7,heading?.55:1.2,24),f=this.folderHeat.get(node.folder),region=.3+.7*(f?f[0]/f[1]:0),alpha=(.18+this.heats[i]*.82)*region*this.alive[i]*(this.focus>=0&&!this.highlight[i]?.06:1)*(this.highlight[i]?1.7:1),flash=this.flash[i]*(1-m),color=this.colors[i].ramps[this.brightness[i]?'hot':'cold'][colorStep];
 if(m<1){ctx.globalAlpha=clamp(alpha*(1-m),0,1);if(s.bloom>0&&(s.quality==='high'||!heading)){const rad=r*(6.4+this.heats[i]*4.2)*s.bloom;ctx.drawImage(this.sprite(color,'halo'),x-rad,y-rad,rad*2,rad*2);}if(s.quality!=='low'){const rad=r*2.6;ctx.drawImage(this.sprite(color,'body'),x-rad,y-rad,rad*2,rad*2);}const rad=Math.max(2,r*1.05)*(1+flash);ctx.drawImage(this.sprite(color,'core'),x-rad,y-rad,rad*2,rad*2);}
 if(m>0){const col=this.brightness[i]?'#FF9E3D':hub>.45?'#E8F0F6':'#9AAAB8';ctx.globalAlpha=clamp(alpha*m*(heading?.65:1),0,1);ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=.65;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.stroke();ctx.globalAlpha*=.12;ctx.fill();ctx.globalAlpha=clamp(alpha*m,0,1);ctx.fillRect(x-.65,y-.65,1.3,1.3);if(!heading&&s.bloom>0){const rad=r*2.5;ctx.globalAlpha=alpha*m*.15*s.bloom;ctx.drawImage(this.sprite(this.brightness[i]?'#FF9E3D':'#E8F0F6','core'),x-rad,y-rad,rad*2,rad*2);}}
 if(flash>.02){const rad=r*(3+flash*4);ctx.globalAlpha=alpha*flash;ctx.drawImage(this.sprite(m>.5?(this.brightness[i]?'#FF9E3D':'#E8F0F6'):color,'core'),x-rad,y-rad,rad*2,rad*2);}
 if(s.names!=='none'&&(s.names==='all'||!heading&&hub>.64||i===this.hover)){ctx.globalAlpha=clamp(alpha*.9,0,1);ctx.fillStyle=m>.5?'#E8F0F6':'#dee8ff';ctx.font='500 10px Manrope, "Avenir Next", sans-serif';ctx.textAlign='center';ctx.letterSpacing=(m*1.6)+'px';if(m<1){ctx.globalAlpha*=1-m;ctx.fillText(this.colors[i].normal,x,y-r-9);}if(m>0){ctx.globalAlpha=clamp(alpha*m,0,1);ctx.fillText(this.colors[i].upper,x,y-r-9);}}}
 ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;if(m>0)this.furniture(m);if(this.frames%12===0){this.contentEl.style.setProperty('--telemetry',String(m));this.readout.style.letterSpacing=(m*.12)+'em';const i=this.hover>=0?this.hover:this.focus;this.tally.textContent=g.noteCount+' NOTES / '+(n-g.noteCount)+' HEADINGS\n'+g.edges.length+' CONNECTIONS';this.subtitle.textContent=m>.5?'Vault telemetry / local system':'A living atlas of your thinking';const line=j=>{const x=g.nodes[j];return x.path+'\n'+(x.kind==='heading'?x.name+'\n':'')+x.degree+' connections · '+(x.heatDays<1?'today':Math.floor(-Math.log(Math.max(this.heats[j],1e-9))*18)+' days ago')+' · '+x.commits+' revisions';};this.readout.textContent=(this.focus>=0?'HELD · '+line(this.focus)+'\n'+this.branchCount+' in branch · reach '+this.reach+(this.isolating?' · isolated':'')+(this.trail.length?' · '+this.trail.length+' back':'')+(this.hover>=0&&this.hover!==this.focus?'\n▸ '+g.nodes[this.hover].name:''):i>=0?line(i):'Drag to explore the whole\nClick a point to follow its connections, again to open')+'\n'+(this.playStart!==null?new Date(this.playTime).toISOString().slice(0,10)+' / history playback':(this.yaw*180/Math.PI%360).toFixed(1)+'° / '+s.vantage+(this.historyAvailable?' / git history':' / filesystem fallback'));}}
 furniture(alpha){const c=this.ctx,w=this.w,h=this.h;c.globalAlpha=alpha*.6;c.strokeStyle='#6E7C8C';c.lineWidth=.6;c.beginPath();for(const x of [18,w-18])for(const y of [18,h-18]){const dx=x<w/2?1:-1,dy=y<h/2?1:-1;c.moveTo(x,y+22*dy);c.lineTo(x,y);c.lineTo(x+22*dx,y);}for(let i=0;i<60;i++){const a=i/60*TAU,r=Math.min(w,h)*.43,len=i%5===0?7:3;c.moveTo(w/2+Math.cos(a)*r,h/2+Math.sin(a)*r);c.lineTo(w/2+Math.cos(a)*(r+len),h/2+Math.sin(a)*(r+len));}c.stroke();c.globalAlpha=alpha*.22;c.beginPath();for(const k of [.22,.43]){c.moveTo(w/2+Math.min(w,h)*k,h/2);c.arc(w/2,h/2,Math.min(w,h)*k,0,TAU);}c.stroke();c.globalAlpha=1;}
 async onClose(){this.closed=true;this.win?.cancelAnimationFrame(this.raf);this.raf=0;this.resizeObserver?.disconnect();this.intersection?.disconnect();this.sprites.clear();}
}
class CortexPlugin extends Plugin{
 async onload(){this.settings={...DEFAULTS,...await this.loadData()};FOLDER_OVERRIDE=this.settings.folders||{};this.history=null;this.pending=null;this.dead=false;this.registerView(TYPE,leaf=>new CortexView(leaf,this));this.addRibbonIcon('smartphone','Open Cortex',()=>this.open());this.addCommand({id:'open-view',name:'Open view',callback:()=>this.open()});const refresh=()=>{clearTimeout(this.timer);this.timer=setTimeout(async()=>{this.history=null;for(const leaf of this.app.workspace.getLeavesOfType(TYPE))if(leaf.view instanceof CortexView)try{await leaf.view.refresh();}catch(e){console.error('Cortex refresh failed',e);}},5000);};this.registerEvent(this.app.metadataCache.on('changed',refresh));this.registerEvent(this.app.metadataCache.on('resolved',refresh));for(const event of ['create','delete','rename'])this.registerEvent(this.app.vault.on(event,refresh));this.register(()=>clearTimeout(this.timer));}
 async open(){let leaf=this.app.workspace.getLeavesOfType(TYPE)[0];if(!leaf){leaf=this.app.workspace.getLeaf('tab');await leaf.setViewState({type:TYPE,active:true});}await this.app.workspace.revealLeaf(leaf);}
 async readHistory(){if(this.history)return this.history;if(this.pending)return this.pending;this.pending=new Promise(resolve=>{const base=this.app.vault.adapter.getBasePath?.();if(!base){console.warn('Cortex: git history unavailable; using filesystem mtime.');resolve(new Map());return;}resolve(new Map());});try{this.history=await this.pending;return this.history;}finally{this.pending=null;}}
 async graph(){const history=await this.readHistory();return buildGraph(this.app.vault.getMarkdownFiles(),f=>this.app.metadataCache.getFileCache(f),this.app.metadataCache.resolvedLinks,history);}
 onunload(){this.dead=true;clearTimeout(this.timer);for(const leaf of this.app.workspace.getLeavesOfType(TYPE))if(leaf.view instanceof CortexView){leaf.view.closed=true;leaf.view.win?.cancelAnimationFrame(leaf.view.raf);leaf.view.resizeObserver?.disconnect();leaf.view.intersection?.disconnect();}}
}
module.exports=CortexPlugin;
module.exports.testing={parseHistory,lastAt,buildGraph,Layout};
